export const bands = {
  'so-long-goodnight': {
    slug: 'so-long-goodnight',
    name: 'So Long Goodnight',
    shortName: 'SLGN',
    tagline: "The Warped Tour era. Live.",
    description: "So Long Goodnight is a 3+ hour, 100+ song run through the Warped Tour era. Brand New, Taking Back Sunday, My Chemical Romance, Thursday, Senses Fail, The Used, Hawthorne Heights. Loud, live, and sung back word for word. If you ever owned an Atticus shirt, this band is for you.",
    genre: ['2000s Emo', 'Pop Punk', 'Post-Hardcore'],
    era: 'Warped Tour Era',
    color: '#00B4D8',
    colorDark: '#005F73',
    colorRgb: '0, 180, 216',
    bookingEmail: 'slgn@echoplay.live',
    airtableId: 'recOyzMS2M0z99hYL',
    social: {
      facebook: 'https://www.facebook.com/slgnband',
      instagram: 'https://www.instagram.com/slgnband',
      bandsintown: 'https://www.bandsintown.com/a/15624562',
    },
    pattern: 'wave',
    hideTagline: true,
    experienceHeadline: { line1: 'The Kind of Show', line2: 'People Talk About' },
    experienceBody: "At an SLGN show, the room participates. Sing-alongs the second a song everyone forgot they remembered hits. Pits forming. People you came with, people you didn't, finding each other by the third chorus. It's not nostalgia. It's the Warped Tour you remember, still running.",
    experiencePoints: ['3+ Hours Live', '100+ Songs', 'Sing-Along Crowd'],
    history: [
      { year: 'The Idea', label: 'Born From the Pit', text: 'So Long Goodnight started with a simple read on the room. Nobody in DFW was bringing back the Warped Tour era live the way it deserved. Not the full-band energy. Not the right catalog. Not the way fans needed to hear the songs they grew up on. The founders were Warped Tour kids who decided to do it themselves.' },
      { year: 'The Sound', label: '3+ Hours, No Filler', text: 'From the beginning, SLGN committed to a 3+ hour set of nothing but the real thing. Brand New, Taking Back Sunday, Thursday, The Used, Hawthorne Heights, Senses Fail. Loud, live, and sung back word for word. The reputation for marathon sets that never lose energy became the first thing people mentioned when they talked about SLGN.' },
      { year: 'The Following', label: 'Word of Mouth', text: 'Venues that booked SLGN once kept booking them. The crowds weren\'t passive. Singing every word, crowd surfing, forming pits, finding each other the way only emo kids can. One-time bookings turned into recurring residencies. Word of mouth turned into a real Metroplex following.' },
      { year: 'Texas Live', label: 'Headlining Texas Live', text: 'In 2026, SLGN played Texas Live in Arlington, one of the biggest entertainment venues in the Metroplex. The room came specifically for them. That show confirmed what had already been building. SLGN had graduated from being a local act to being an event.' },
      { year: 'Now', label: 'Still in the Pit', text: 'Years in, So Long Goodnight remains one of Echo Play Live\'s most booked acts. The setlist keeps growing. The pits keep opening. If you grew up on Warped Tour, SLGN is the closest thing to going back.' },
    ],
    stats: [
      { value: '3+ Hours', label: 'Per Show' },
      { value: '100+', label: 'Songs' },
      { value: 'Sing-Along', label: 'Show' },
      { value: 'Warped Tour', label: 'Era' },
    ],
    heroObjectPosition: 'center 20%',
  },

  'the-dick-beldings': {
    slug: 'the-dick-beldings',
    name: 'The Dick Beldings',
    shortName: 'TDB',
    tagline: "Your 90s Playlist… Live.",
    description: "It started on a patio in downtown Fort Worth. Aaron and Paul were watching a crowd lose their minds over 80s covers and had a simple thought: we should do that with 90s music. Over a decade later, The Dick Beldings have become one of DFW's most beloved live acts. Five guys who genuinely love these songs, playing them the way you remember them. Songs that make you spit out your beer and yell: \"I love that song!\"",
    genre: ['90s Rock', 'Alternative', 'Grunge'],
    era: '90s Alternative Era',
    color: '#FF6B35',
    colorDark: '#C1440E',
    colorRgb: '255, 107, 53',
    bookingEmail: 'dickbeldings@echoplay.live',
    airtableId: 'recMY8s33mfIQKr3S',
    social: {
      facebook: 'https://www.facebook.com/TheDickBeldings',
      instagram: 'https://www.instagram.com/thedickbeldings',
      bandsintown: 'https://www.bandsintown.com/a/3177952',
    },
    pattern: 'grid',
    experienceHeadline: { line1: 'The Room Changes', line2: 'When They Play' },
    experienceBody: "There's something that happens in a Dick Beldings crowd that you can't manufacture. Someone recognizes the first four notes of a song and loses it. Then the person next to them loses it. Then the whole room is singing something they haven't thought about since high school and absolutely cannot stop smiling. That's what over a decade of playing these songs with genuine love looks like from the stage.",
    experiencePoints: ['Over a Decade Live', 'Authentic 90s Catalog', 'Fort Worth Originals'],
    history: [
      { year: 'The Origin', label: 'A Patio in Fort Worth', text: 'Aaron and Paul were watching a Spasmatic show in downtown Fort Worth when it clicked. The crowd was losing it over 80s covers. The thought was immediate: we should do that with 90s music. Ben Dunlap was there too. By the end of the night, the Dick Beldings existed in concept. Within weeks, they were practicing in Jenna\'s living room.' },
      { year: 'First Practice', label: 'Jenna\'s Living Room', text: 'Michael Harper came aboard through a mutual connection. Aaron\'s roommate Jenna worked with Michael\'s wife Rachel. They crammed into Jenna\'s living room and ran through Death Cab for Cutie, Spin Doctors, Jimmy Eat World, and whatever else felt right. Paul and Ben had history too. They\'d played together years earlier in a high school punk band doing Blink-182 covers. The bones were already there.' },
      { year: 'Spencer\'s Corner', label: '$0.25 Whiskey Cokes', text: 'Their first show was a Sunday warm-up at Spencer\'s Corner near Ridgemar Mall, a legendary Fort Worth dive with $0.25 whiskey Cokes, a checkerboard dance floor, and an unforgettable cast of regulars. The official first booked show followed at The Aardvark. Spencer\'s became home base. Those Sunday nights started with just friends in the crowd and kept growing until the place eventually closed (reportedly due to tax issues, hard to profit on $0.25 drinks).' },
      { year: 'The Venues', label: 'Wild Rooster to Texas Live', text: 'From Spencer\'s, the Beldings moved through Fort Worth\'s best rooms. The Wild Rooster, Uptown Tavern, O\'Shea\'s, Queen City Music Hall. Each step up brought bigger crowds and longer nights. The Rooster had its own lore: Ben met Stephanie there, proposed at the Rooster too. By the time they hit Texas Live in Arlington for All-Star Game residencies, the Beldings were one of DFW\'s most recognizable live acts.' },
      { year: 'Now', label: 'Still the 90s, Still Live', text: 'The Dick Beldings are still playing. Still making rooms react the way they always have. Vaseline into Two Princes into What I Got. Songs you know by heart, played by guys who mean every note. Over a decade of shows and the setlist keeps getting sharper.' },
    ],
    stats: [
      { value: '10+', label: 'Years Together' },
      { value: 'Fort Worth', label: 'Based' },
      { value: '90s', label: 'Era' },
      { value: '100+', label: 'Song Library' },
    ],
    heroObjectPosition: 'center 20%',
    heroPhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/The%20Dick%20Beldings/Media/485014123_1207420204723031_5733840107378899544_n%20%281%29.jpg',
    featurePhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/The%20Dick%20Beldings/Media/156A6105.jpg',
    crowdPhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/The%20Dick%20Beldings/Media/156A6129.jpg',
  },

  'jambi': {
    slug: 'jambi',
    name: 'Jambi',
    shortName: 'JAMBI',
    tagline: "A TOOL Experience",
    description: "Jambi doesn't replicate TOOL. They channel it. Years of rehearsal, study, and refinement have produced a show built around what TOOL's music actually is: tension, release, the spiritual weight of songs that take you somewhere. From their debut at Gas Monkey Bar n' Grill to headlining Granada Theater and Legacy Hall, Jambi has earned a reputation in Texas for treating the catalog the way Tool fans expect it to be treated.",
    genre: ['Progressive Metal', 'Art Rock', 'Psychedelic'],
    era: 'Progressive Metal',
    color: '#9D4EDD',
    colorDark: '#5A189A',
    colorRgb: '157, 78, 221',
    bookingEmail: 'jambi@echoplay.live',
    airtableId: 'recOP9WYkvMajk16S',
    social: {
      facebook: 'https://www.facebook.com/JambiToolTribute',
      bandsintown: 'https://www.bandsintown.com/a/15624564',
    },
    pattern: 'spiral',
    experienceHeadline: { line1: "You Don't Watch Jambi.", line2: 'You Feel It.' },
    experienceBody: "TOOL audiences are a specific kind of listener. Patient, attentive, impossible to fake out. Jambi earns that crowd every night. The songs are played with the precision and intentionality the music demands, and the room responds the way a TOOL room responds: completely absorbed. People come in skeptical and walk out asking when the next show is. That's the standard Jambi holds itself to.",
    experiencePoints: ['Faithful to the Catalog', 'Precision Performance', 'Immersive Show'],
    history: [
      { year: '2018', label: 'Founded in Fort Worth', text: 'Jambi was born in Fort Worth as The Tools with one mission: to do full justice to TOOL\'s catalog live. The band spent months in rehearsal before ever stepping on a stage. Studying not just the notes but the feel, the dynamics, the weight of every song. TOOL\'s music is among the most technically demanding and emotionally complex in rock. The goal wasn\'t to cover it. It was to understand it.' },
      { year: '2019', label: 'Gas Monkey Bar n\' Grill Debut', text: 'March 2019. Their headlining debut at Gas Monkey Bar n\' Grill, one of the most recognizable venues in DFW. The bill included a System of a Down tribute and a Nine Inch Nails tribute. From that first night, audiences knew this was something different from a typical tribute show. The room felt it. Word started spreading through DFW\'s metal community immediately.' },
      { year: '2019–2022', label: 'Building the Following', text: 'O\'Sheas in Hurst became home base. A room that kept calling them back because the crowds kept showing up. They played The Granada Theater, The Pour Shack in Keller, Ridglea Room in Fort Worth, and Chill in Lewisville. Regular co-bills with a Rise Against the Machine tribute became one of DFW\'s most anticipated metal nights. The fanbase was growing show by show.' },
      { year: '2022–2024', label: 'Bigger Rooms, Bigger Bills', text: 'Beer City Music Hall, the Haltom Theater, a first Oklahoma City appearance. The following was spreading beyond DFW. Regular co-headlining with Elite (Deftones), Nine-ish Nails (NIN), Primish (Primus), and Beware! Criminals (Incubus) established Jambi as the anchor of a thriving tribute metal scene. Granada became a recurring headline stop. Audiences from across North Texas were making the drive.' },
      { year: '2025', label: 'Jambi: A New Era', text: 'Early 2025 brought a rebrand and a new chapter under Echo Play Live. The first show as Jambi (March 1st at O\'Sheas) sold out and felt like a celebration. Since then: Legacy Hall, a Granada Theater headliner, a Lubbock date at Jake\'s Sports Cafe, and a TOOL & PRIMUS Tribute Night at O\'Sheas with Primish that brought together two of DFW\'s strongest metal tribute acts. The name changed. The standard didn\'t.' },
    ],
    stats: [
      { value: '50+', label: 'Shows Performed' },
      { value: '2019', label: 'Est.' },
      { value: '6 Years', label: 'On Stage' },
      { value: 'TX & OK', label: 'Territory' },
    ],
    heroObjectPosition: 'center 20%',
    heroPhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/Jambi/Media/7-B1500592-81AB-4D02-A952-E2C23A6BD777_1_105_c.jpg',
    featurePhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/Jambi/Media/11-6FA12D4C-8B9F-478B-8551-DD2A9AC79AFA_1_105_c.jpg',
    crowdPhoto: 'https://wkqcpwrvrb9fa0hy.public.blob.vercel-storage.com/Jambi/Media/41-6F34CBD5-B6B5-448D-984B-CE8F0DED63FC_1_105_c.jpg',
  },

  'elite': {
    slug: 'elite',
    name: 'Elite',
    shortName: 'ELITE',
    tagline: "A Texas Tribute to Deftones",
    description: "Elite has been bringing Deftones to Texas stages since 2017. In that time they've become the standard for what a Deftones tribute should feel like. Heavy when it needs to be heavy, delicate when the song calls for it, always honest. The Deftones catalog demands that kind of range, and Elite delivers it. From O'Sheas in Hurst to the Granada Theater in Dallas, audiences keep coming back because the show doesn't just sound right. It feels right.",
    genre: ['Alternative Metal', 'Shoegaze'],
    era: 'Alternative Metal',
    color: '#E63946',
    colorDark: '#9D0208',
    colorRgb: '230, 57, 70',
    bookingEmail: 'elite@echoplay.live',
    airtableId: 'recJrGyEPjO5xJ10Z',
    social: {
      facebook: 'https://www.facebook.com/EliteDeftones',
      instagram: 'https://www.instagram.com/elitedeftones',
      bandsintown: 'https://www.bandsintown.com/a/15624563',
    },
    pattern: 'diagonal',
    experienceHeadline: { line1: 'Heavy. Delicate.', line2: 'Exactly Like Deftones.' },
    experienceBody: "Deftones fans are not casual listeners. They know every dynamic shift, every moment where the song opens up or pulls back. Elite respects that. The shows are built for the people who've listened to White Pony a hundred times and the people who are discovering what the noise is about. What they have in common when they walk out: they want to come back.",
    experiencePoints: ['8 Years On Stage', 'Full Catalog Performed', 'Fort Worth Based'],
    history: [
      { year: '2017', label: 'Founded in Fort Worth', text: 'Elite launched in February 2017 with a clear purpose: to be the Deftones tribute that Fort Worth and DFW deserved. The Deftones have one of the most devoted fanbases in rock. People who don\'t just love the band, they feel it. Elite was built by musicians who felt it too, and who understood that doing the music justice meant honoring both its heaviness and its vulnerability.' },
      { year: '2017–2022', label: 'Earning the Reputation', text: 'Early shows at O\'Sheas in Hurst established what Elite was about. The room would go heavy and then get quiet in exactly the right places. The atmospheric swings that make Deftones genuinely unlike any other band. Fans spread the word. Invitations from other tribute acts started coming in. By 2023, Elite was getting co-headlining requests from Rise Against the Machine tributes and nu-metal nights, recognized as one of the most consistent draws in the scene.' },
      { year: '2023', label: 'The Jambi Partnership', text: 'The pairing of Elite and Jambi (Deftones and TOOL, two bands that share a fanatical fanbase and a philosophy about what rock music can be) became one of the most popular tribute nights in DFW. Their co-headline shows at O\'Sheas consistently packed the room. Lubbock\'s Jake\'s Sports Cafe brought them out of DFW together in 2025 to a crowd that traveled specifically for the double bill.' },
      { year: '2024–2025', label: 'Granada, Haltom & Beyond', text: 'Elite stepped into bigger rooms and held them. Granada Theater in Dallas, Nu Metal Fest at the Haltom Theater alongside (SiC), Lost in Hollywood, and Jambi. Shows in Lubbock. The fanbase followed them out of DFW and started growing beyond it. Every new market they play, they leave with fans asking when they\'re coming back.' },
      { year: 'Now', label: 'Still Bleeding', text: 'Elite plays the full Deftones catalog, from Adrenaline through Ohms, and keeps expanding the setlist as the years add more music worth playing. Eight years in, the band is sharper, the setlists are deeper, and the shows keep drawing the kind of crowd that knows every word of every song they play. Heavy, honest, and entirely Texas.' },
    ],
    stats: [
      { value: '2017', label: 'Est.' },
      { value: '8 Years', label: 'On Stage' },
      { value: 'Fort Worth', label: 'Based' },
      { value: 'TX & Beyond', label: 'Territory' },
    ],
    heroObjectPosition: 'center 20%',
  },
}

export const bandsList = Object.values(bands)

export function getBand(slug) {
  return bands[slug] || null
}

export const bandNameToSlug = {
  'So Long Goodnight': 'so-long-goodnight',
  'The Dick Beldings': 'the-dick-beldings',
  'Jambi': 'jambi',
  'Elite': 'elite',
}
