export const SPECIALIST_GUIDES = {
  advance: {
    kind: 'advance',
    label: 'Show Advance',
    shortLabel: 'Advance',
    group: 'Show Ops',
    risk: 'Low',
    approval: false,
    tagline: 'Turns a booked show into a clear day-of operating plan.',
    mission: 'The Advance specialist exists to remove show-day ambiguity. It reads the show record, finds missing logistics, creates venue questions, and turns the date into a practical call-sheet style plan.',
    bestFor: ['Preparing for a show within the next 30 days', 'Finding missing load-in, soundcheck, contact, parking, and merch details', 'Creating venue advance questions', 'Turning scattered show notes into a usable show-day checklist'],
    notFor: ['Sending the venue email automatically', 'Changing deal terms', 'Approving final settlement', 'Replacing human confirmation from the venue'],
    inputs: ['Show date, venue, band, start time, load-in, soundcheck', 'Members playing, sound engineer, merch person', 'Venue contact, address, parking, production notes', 'Internal show, sound, and merch notes'],
    outputs: ['Call-sheet snapshot', 'Readiness checklist', 'Venue questions', 'Open items', 'Recommended next actions that can become tasks'],
    guardrails: ['Internal planning is safe to log automatically.', 'Venue-facing language should be reviewed before sending.', 'Anything that confirms a booking detail externally should go through approval or Gmail draft review.'],
    playbook: ['Run Advance first for shows with missing logistics.', 'Convert its recommended next actions into tasks.', 'Use the output to update Show Notes, Sound Notes, and Merch Notes.', 'Run it again after details are filled to confirm show readiness.'],
    goodPrompt: 'Build me a venue advance plan for this show. Focus on what is still missing, what we need from the venue, and what should become tasks.',
  },
  promo: {
    kind: 'promo',
    label: 'Promo Plan',
    shortLabel: 'Promo',
    group: 'Marketing',
    risk: 'Medium',
    approval: true,
    tagline: 'Creates review-ready show copy, captions, and promo cadence.',
    mission: 'The Promo specialist helps turn show data into public-facing language. It should keep copy useful, readable, and venue-ready without sounding like generic AI marketing.',
    bestFor: ['Writing event blurbs', 'Creating social caption angles', 'Planning announcement, reminder, and day-of cadence', 'Preparing copy for Facebook, Bandsintown, venue calendars, and email'],
    notFor: ['Posting publicly without approval', 'Inventing ticket details', 'Changing show facts to make copy sound better', 'Using internal notes in public copy'],
    inputs: ['Band, venue, date, start time, ticket details, age restriction', 'Show theme, hook, event description, approved graphics', 'Ticket URL and public status'],
    outputs: ['Short event copy', 'Medium event copy', 'Listing copy', 'Caption angles', 'Promo schedule', 'Public-readiness warnings'],
    guardrails: ['Public copy requires review.', 'No posting until ticket, date, venue, and time are confirmed.', 'Use plain language over hype when the facts are incomplete.'],
    playbook: ['Run Promo after show basics are confirmed.', 'Send useful copy to the approval queue.', 'Turn cadence items into tasks.', 'Use Web / SEO after Promo if the show will be public on the site.'],
    goodPrompt: 'Create a promo plan that sounds human and not overly salesy. Give me event copy, caption angles, and what needs to be confirmed before posting.',
  },
  design: {
    kind: 'design',
    label: 'Design Brief',
    shortLabel: 'Design',
    group: 'Creative',
    risk: 'Medium',
    approval: true,
    tagline: 'Turns show details into a Canva-ready creative brief.',
    mission: 'The Design specialist makes creative work easier to execute by defining the required text, visual direction, assets, safe areas, and deliverable sizes before anyone starts designing.',
    bestFor: ['Show flyer briefs', 'Canva prompt prep', 'Asset checklist', 'Sizing requirements', 'Making sure graphics are readable on mobile'],
    notFor: ['Publishing or changing final art without approval', 'Inventing logos or band photos', 'Approving AI artifacts', 'Replacing final human visual review'],
    inputs: ['Band identity, venue, date, show time, ticket info, age restriction', 'Approved band photos, logos, brand guides, venue requests', 'Needed formats like square, 4:5, story, event header, page header'],
    outputs: ['Creative brief', 'Required text list', 'Asset needs', 'Deliverable size list', 'Quality rules', 'Design risks'],
    guardrails: ['Never bury date, venue, or band name.', 'Graphics should be reviewed before public release.', 'Avoid fake AI hands, fake crowd artifacts, and unreadable text.'],
    playbook: ['Run Design before creating graphics.', 'Use its required text list as the source of truth.', 'Create tasks for missing photos, logos, ticket links, or QR codes.', 'Run Promo after Design when graphics are ready.'],
    goodPrompt: 'Build a design brief for this show. Focus on what text must be on the graphic, what assets are missing, and how to make it readable on phone.',
  },
  booking: {
    kind: 'booking',
    label: 'Booking / Venue CRM',
    shortLabel: 'Booking',
    group: 'Revenue',
    risk: 'High',
    approval: true,
    tagline: 'Helps manage venue follow-up, deal questions, and relationship context.',
    mission: 'The Booking specialist protects the business side of each show. It summarizes venue context, identifies deal or follow-up gaps, and drafts relationship-aware next touches for review.',
    bestFor: ['Venue follow-up drafts', 'Checking if a show is missing contract, rate, or deal details', 'Relationship notes', 'Preparing a booking or confirmation email draft', 'Identifying who owes who a response'],
    notFor: ['Sending email automatically', 'Confirming dates without approval', 'Changing financial terms', 'Speaking for Evan without review'],
    inputs: ['Venue, contact, show status, deal type, performance rate', 'Contract status, prior notes, email/thread summary when available', 'Open show details and next step'],
    outputs: ['CRM snapshot', 'Suggested next touch', 'Deal questions', 'Follow-up draft', 'Risk notes', 'Tasks'],
    guardrails: ['External communication requires review.', 'Deal changes are high-risk and must be approved.', 'When uncertain, draft questions rather than assumptions.'],
    playbook: ['Run Booking when a venue detail is unclear or a response is needed.', 'Use Gmail/thread context when available.', 'Create tasks for follow-up dates.', 'Use approvals before sending anything external.'],
    goodPrompt: 'Review this show like a booking manager. What is missing, what should I ask the venue, and what follow-up should I send after review?',
  },
  finance: {
    kind: 'finance',
    label: 'Finance / Settlement',
    shortLabel: 'Finance',
    group: 'Finance',
    risk: 'Medium',
    approval: false,
    tagline: 'Checks money fields, payout readiness, expenses, and settlement risks.',
    mission: 'The Finance specialist keeps every show financially understandable. It should identify missing deal fields, expenses, and payout assumptions before settlement becomes confusing.',
    bestFor: ['Settlement prep', 'Checking payout fields', 'Identifying missing expenses', 'Reviewing deal type, rate, EPL percent, and band payout', 'Creating a pre-show or post-show finance checklist'],
    notFor: ['Changing payout numbers automatically', 'Approving final settlement without review', 'Giving tax or legal advice', 'Making assumptions about missing deal terms'],
    inputs: ['Deal type, ticket price, performance rate, EPL percent', 'Trailer, audio, ads, merch, and other expenses', 'Total expenses, net income, band payout'],
    outputs: ['Settlement snapshot', 'Missing money fields', 'Risk notes', 'Payout checklist', 'Internal next actions'],
    guardrails: ['Financial changes require human review.', 'Missing fields should become tasks, not assumptions.', 'Settlement should not be final until all expenses are entered.'],
    playbook: ['Run Finance during show week and after the show.', 'Create tasks for missing deal or expense fields.', 'Use the result to update finance notes or settlement workflow.', 'Do not treat output as final payout approval.'],
    goodPrompt: 'Audit this show financially. Tell me what fields are missing, what could affect payout, and what needs to be done before settlement.',
  },
  content: {
    kind: 'content',
    label: 'Content Capture',
    shortLabel: 'Content',
    group: 'Content',
    risk: 'Medium',
    approval: true,
    tagline: 'Plans what needs to be filmed, photographed, collected, and posted later.',
    mission: 'The Content specialist makes sure each show creates proof: crowd energy, band quality, venue vibe, and usable material for future promo.',
    bestFor: ['Shot lists', 'Reel plans', 'Assigning capture roles', 'Planning post-show recap assets', 'Making sure footage gets collected before everyone leaves'],
    notFor: ['Posting recap content without review', 'Using bad or artifact-heavy media', 'Replacing final creative judgment', 'Ignoring venue or crowd privacy concerns'],
    inputs: ['Show details, band, venue, room type, expected crowd', 'Available crew, phones/cameras, Drive folder', 'Desired recap, trailer, or social content'],
    outputs: ['Capture brief', 'Must-capture list', 'Reel structure', 'Assignment ideas', 'Asset collection plan'],
    guardrails: ['Public recap copy requires review.', 'Do not assume every clip is usable.', 'Collect footage in Drive or a clear folder so it does not disappear in texts.'],
    playbook: ['Run Content before show day.', 'Create tasks for who captures what.', 'Use Drive for asset collection.', 'Run Promo or Web after the show for recap language.'],
    goodPrompt: 'Create a content capture plan for this show. Give me must-have shots, who should capture them, and what tasks we need before show day.',
  },
  web: {
    kind: 'web',
    label: 'Web / SEO',
    shortLabel: 'Web',
    group: 'Website',
    risk: 'Medium',
    approval: true,
    tagline: 'Checks public listing readiness, SEO basics, ticket links, and website-safe copy.',
    mission: 'The Web specialist protects the public website. It verifies that a show is ready to be public, flags missing details, and drafts safe metadata or listing language.',
    bestFor: ['Public listing audits', 'Ticket-link checks', 'SEO title and description drafts', 'Publish-to-website readiness', 'Checking that public copy does not leak internal notes'],
    notFor: ['Publishing shows without the public gate', 'Changing website copy without review', 'Indexing private admin pages', 'Inventing event details'],
    inputs: ['Publish to Website status, show date, band, venue, ticket link', 'Public copy, age restriction, start time', 'Meta title, description, route readiness'],
    outputs: ['Listing audit', 'SEO draft', 'QA checklist', 'Public-readiness recommendation', 'Tasks'],
    guardrails: ['Public website changes require review.', 'Admin, portal, and API routes remain noindex/private.', 'Core public content should be available in raw HTML where possible.'],
    playbook: ['Run Web before enabling a show publicly.', 'Create tasks for missing ticket, time, or copy details.', 'Use it after Promo to align website copy.', 'Use system diagnostics for deployment/indexing checks.'],
    goodPrompt: 'Audit this show for the website. Should it be public yet? What SEO copy should we use and what must be fixed before publishing?',
  },
  merch: {
    kind: 'merch',
    label: 'Merch Ops',
    shortLabel: 'Merch',
    group: 'Show Ops',
    risk: 'Low',
    approval: false,
    tagline: 'Prepares merch table, POS, inventory, staffing, and closeout flow.',
    mission: 'The Merch specialist makes the merch operation easy to run at the venue and easy to settle afterward.',
    bestFor: ['Merch table setup', 'Square/POS reminders', 'Inventory checks', 'Assigning merch person', 'Post-show closeout notes'],
    notFor: ['Changing prices without approval', 'Finalizing settlement alone', 'Replacing physical inventory count', 'Making financial assumptions'],
    inputs: ['Merch person, venue setup, POS device, inventory notes', 'Show date, expected crowd, merch costs, settlement notes'],
    outputs: ['Setup checklist', 'POS and supplies list', 'Sales notes', 'Inventory reminders', 'Post-show closeout tasks'],
    guardrails: ['Prices and comps should be confirmed before show day.', 'Cash counts and inventory should be verified by a person.', 'Financial results should feed Finance / Settlement.'],
    playbook: ['Run Merch during show week.', 'Create tasks for staffing, POS, and inventory.', 'Update Merch Notes after the show.', 'Run Finance afterward if merch affects settlement.'],
    goodPrompt: 'Build a merch ops checklist for this show. Tell me what to bring, who needs to be assigned, and what needs to be tracked after the show.',
  },
}

export function specialistGuideOptions() {
  return Object.values(SPECIALIST_GUIDES)
}

export function getSpecialistGuide(kind) {
  return SPECIALIST_GUIDES[kind] || null
}
