// /press — Echo Play Live press & EPK page.
//
// Phase 17: single landing surface for press inquiries. Logo downloads (SVG +
// 1024 PNG, three colorways), a one-pager PDF per band (auto-generated by
// /api/press/[slug]), and contact info. Per-band booking emails surface here
// so promoters can route inquiries directly without going through the contact
// form.

'use client'
import { useEffect, useRef } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import Nav from '@/components/Nav'
import FaqSection from '@/components/FaqSection'
import { FAQ_PRESS } from '@/lib/faqs'
import Footer from '@/components/Footer'
import { bandsList } from '@/lib/bands'

function useScrollReveal() {
  const ref = useRef(null)
  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('revealed') }),
      { threshold: 0.1, rootMargin: '0px 0px -40px 0px' }
    )
    const els = ref.current?.querySelectorAll('.reveal, .reveal-left, .reveal-right, .reveal-up')
    els?.forEach(el => observer.observe(el))
    return () => observer.disconnect()
  }, [])
  return ref
}

// EPL master logo download files. Both SVG and 1024px PNG provided for each
// colorway. Files live in /public/press/.
const eplLogoDownloads = [
  { label: 'EPL Logo · White on transparent',  svg: '/press/epl-logo-white.svg',  png: '/press/epl-logo-white-1024.png',  swatch: '#ffffff', dark: false },
  { label: 'EPL Logo · Gold on transparent',   svg: '/press/epl-logo-gold.svg',   png: '/press/epl-logo-gold-1024.png',   swatch: '#D4A017', dark: false },
  { label: 'EPL Logo · Black on transparent',  svg: '/press/epl-logo-black.svg',  png: '/press/epl-logo-black-1024.png',  swatch: '#080808', dark: true  },
]

export default function PressPage() {
  const pageRef = useScrollReveal()

  return (
    <>
      <Nav />
      <main ref={pageRef} style={{ background: 'var(--c-bg)', minHeight: '100vh' }}>

        {/* ── HERO ──────────────────────────────────────────────────── */}
        <section style={{
          padding: 'clamp(120px, 16vw, 200px) var(--gutter-fluid) clamp(60px, 8vw, 100px)',
          position: 'relative',
          overflow: 'hidden',
          borderBottom: '1px solid var(--c-border)',
        }}>
          <div style={{
            position: 'absolute', inset: 0,
            background: 'radial-gradient(ellipse 80% 60% at 80% 40%, rgba(212,160,23,0.04) 0%, transparent 60%)',
          }} />
          {/* Big text watermark */}
          <div aria-hidden="true" style={{
            position: 'absolute',
            fontFamily: 'var(--ff-display)',
            fontSize: 'clamp(120px, 30vw, 400px)',
            right: '-0.05em', bottom: '-0.1em',
            lineHeight: 0.8,
            color: 'rgba(212,160,23,0.03)',
            pointerEvents: 'none',
            letterSpacing: '-0.02em',
            userSelect: 'none',
          }}>EPK</div>

          <div style={{ maxWidth: 'var(--layout-max)', margin: '0 auto', position: 'relative' }}>
            <div className="section-label reveal" style={{ marginBottom: '16px' }}>For Press · Venues · Promoters</div>
            <h1 className="reveal delay-100" style={{
              fontFamily: 'var(--ff-display)',
              fontSize: 'clamp(64px, 14vw, 160px)',
              letterSpacing: '0.01em',
              lineHeight: 0.85,
              maxWidth: '900px',
              marginBottom: 'var(--s-5)',
            }}>
              Press &<br />
              <span style={{ color: 'var(--c-epl)' }}>Media Kit</span>
            </h1>
            <p className="reveal delay-200" style={{
              fontFamily: 'var(--ff-body)',
              fontSize: 'clamp(17px, 1.9vw, 21px)',
              lineHeight: 1.7,
              fontWeight: 300,
              color: 'rgba(255,255,255,0.7)',
              maxWidth: '680px',
              marginBottom: 'var(--s-6)',
            }}>
              Everything you need to write us up, book us, or put us on a poster. One-pager PDFs, logo files, and direct booking contacts for every Echo Play Live band.
            </p>
            <div className="reveal delay-300" style={{
              display: 'flex', flexWrap: 'wrap', gap: 'var(--s-3)',
            }}>
              <a href="#bands" style={{
                fontFamily: 'var(--ff-label)',
                fontSize: '12px',
                fontWeight: 600,
                letterSpacing: 'var(--ls-label-tight)',
                textTransform: 'uppercase',
                color: 'var(--c-bg)',
                background: 'var(--c-epl)',
                padding: '14px 24px',
                textDecoration: 'none',
                transition: 'opacity var(--d-fast) var(--ease-in-out)',
              }}
                onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
                onMouseLeave={e => e.currentTarget.style.opacity = '1'}
              >Browse band kits</a>
              <a href="#logos" style={{
                fontFamily: 'var(--ff-label)',
                fontSize: '12px',
                fontWeight: 600,
                letterSpacing: 'var(--ls-label-tight)',
                textTransform: 'uppercase',
                color: 'var(--c-text)',
                background: 'transparent',
                border: '1px solid rgba(255,255,255,0.2)',
                padding: '13px 24px',
                textDecoration: 'none',
                transition: 'border-color var(--d-fast) var(--ease-in-out)',
              }}
                onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--c-epl)'}
                onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)'}
              >Download logos</a>
            </div>
          </div>
        </section>

        {/* ── COMPANY OVERVIEW ──────────────────────────────────────── */}
        <section id="company" style={{
          padding: 'clamp(60px, 10vw, 120px) var(--gutter-fluid)',
          borderBottom: '1px solid var(--c-border)',
        }}>
          <div style={{ maxWidth: 'var(--layout-max)', margin: '0 auto' }}>
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.4fr)',
              gap: 'clamp(40px, 6vw, 80px)',
              alignItems: 'start',
            }} className="press-company-grid">

              {/* Logo lockup */}
              <div className="reveal-up">
                <div style={{
                  aspectRatio: '1 / 1',
                  background: '#0a0a0a',
                  border: '1px solid rgba(255,255,255,0.06)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: 'clamp(24px, 5vw, 56px)',
                  position: 'relative',
                  overflow: 'hidden',
                }}>
                  <Image
                    src="/press/epl-logo-gold.svg"
                    alt="Echo Play Live logo"
                    width={320}
                    height={320}
                    style={{ width: '80%', height: 'auto', display: 'block' }}
                  />
                  <div style={{
                    position: 'absolute', left: 0, right: 0, bottom: 0,
                    height: '3px', background: 'var(--c-epl)',
                  }} />
                </div>
              </div>

              {/* Copy */}
              <div>
                <div className="section-label reveal" style={{ marginBottom: 'var(--s-3)' }}>The Company</div>
                <h2 className="reveal delay-100" style={{
                  fontFamily: 'var(--ff-display)',
                  fontSize: 'clamp(40px, 6vw, 72px)',
                  letterSpacing: '0.01em',
                  lineHeight: 0.95,
                  marginBottom: 'var(--s-5)',
                }}>
                  Echo Play Live
                </h2>
                <p className="reveal delay-200" style={{
                  fontFamily: 'var(--ff-body)',
                  fontSize: 'clamp(15px, 1.7vw, 18px)',
                  lineHeight: 1.8,
                  fontWeight: 300,
                  color: 'rgba(255,255,255,0.7)',
                  marginBottom: 'var(--s-4)',
                }}>
                  Echo Play Live is a Dallas–Fort Worth band management company founded in 2023 by Evan Ranallo. We represent four full-production live acts that play sold-out rooms across Texas and Oklahoma: a 2000s emo / Warped Tour catalog, a 90s alternative show, a TOOL experience, and a Texas tribute to Deftones.
                </p>
                <p className="reveal delay-300" style={{
                  fontFamily: 'var(--ff-body)',
                  fontSize: 'clamp(14px, 1.6vw, 16px)',
                  lineHeight: 1.8,
                  fontWeight: 300,
                  color: 'rgba(255,255,255,0.5)',
                  marginBottom: 'var(--s-6)',
                }}>
                  Quality, hustle, and love for the show. Every band on the roster shares the same standard: real instruments, full sets, every show.
                </p>

                {/* Company facts grid */}
                <div className="reveal-up delay-400" style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
                  gap: '1px',
                  background: 'rgba(255,255,255,0.06)',
                  marginBottom: 'var(--s-6)',
                }}>
                  {[
                    { label: 'Founded', value: '2023' },
                    { label: 'Based In', value: 'DFW, TX' },
                    { label: 'Bands', value: '4 Active' },
                    { label: 'Region', value: 'TX & OK' },
                  ].map(f => (
                    <div key={f.label} style={{
                      background: 'var(--c-bg)',
                      padding: '18px 20px',
                    }}>
                      <div style={{
                        fontFamily: 'var(--ff-label)',
                        fontSize: '9px',
                        fontWeight: 600,
                        letterSpacing: '0.25em',
                        textTransform: 'uppercase',
                        color: 'rgba(255,255,255,0.3)',
                        marginBottom: '4px',
                      }}>{f.label}</div>
                      <div style={{
                        fontFamily: 'var(--ff-display)',
                        fontSize: '22px',
                        letterSpacing: '0.04em',
                        color: 'var(--c-epl)',
                      }}>{f.value}</div>
                    </div>
                  ))}
                </div>

                {/* Booking contact */}
                <div className="reveal-up delay-500" style={{
                  border: '1px solid var(--c-epl-line)',
                  background: 'var(--c-epl-soft)',
                  padding: 'var(--s-5)',
                }}>
                  <div style={{
                    fontFamily: 'var(--ff-label)',
                    fontSize: '10px',
                    fontWeight: 600,
                    letterSpacing: '0.2em',
                    textTransform: 'uppercase',
                    color: 'var(--c-epl)',
                    marginBottom: 'var(--s-2)',
                  }}>Press & Booking · All Bands</div>
                  <a href="mailto:booking@echoplay.live" style={{
                    fontFamily: 'var(--ff-display)',
                    fontSize: 'clamp(22px, 3vw, 30px)',
                    letterSpacing: '0.02em',
                    color: 'var(--c-text)',
                    textDecoration: 'none',
                    display: 'block',
                  }}>booking@echoplay.live</a>
                  <div style={{
                    fontFamily: 'var(--ff-body)',
                    fontSize: '13px',
                    color: 'rgba(255,255,255,0.5)',
                    marginTop: 'var(--s-2)',
                  }}>Or use a band-specific email below for direct routing.</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ── LOGO DOWNLOADS ────────────────────────────────────────── */}
        <section id="logos" style={{
          padding: 'clamp(60px, 10vw, 120px) var(--gutter-fluid)',
          borderBottom: '1px solid var(--c-border)',
          background: 'var(--c-surface-2)',
        }}>
          <div style={{ maxWidth: 'var(--layout-max)', margin: '0 auto' }}>
            <div className="reveal" style={{ marginBottom: 'var(--s-7)' }}>
              <div className="section-label" style={{ marginBottom: 'var(--s-3)' }}>Brand Assets</div>
              <h2 style={{
                fontFamily: 'var(--ff-display)',
                fontSize: 'clamp(40px, 6vw, 72px)',
                letterSpacing: '0.01em',
                lineHeight: 0.95,
                marginBottom: 'var(--s-3)',
              }}>EPL Logo Downloads</h2>
              <p style={{
                fontFamily: 'var(--ff-body)',
                fontSize: 'clamp(14px, 1.6vw, 16px)',
                lineHeight: 1.7,
                fontWeight: 300,
                color: 'rgba(255,255,255,0.55)',
                maxWidth: '640px',
              }}>
                Vector SVG for print and signage, 1024 PNG for web and social. Please don't recolor, distort, or place on backgrounds that compromise legibility.
              </p>
            </div>

            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
              gap: 'var(--s-4)',
            }}>
              {eplLogoDownloads.map((logo, i) => (
                <div
                  key={logo.label}
                  className={`reveal-up delay-${(i + 1) * 100}`}
                  style={{
                    border: '1px solid rgba(255,255,255,0.06)',
                    background: 'var(--c-bg)',
                    overflow: 'hidden',
                    display: 'flex',
                    flexDirection: 'column',
                  }}
                >
                  {/* Preview swatch with logo */}
                  <div style={{
                    aspectRatio: '1 / 1',
                    background: logo.dark ? '#f5f5f5' : '#0a0a0a',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    padding: '20%',
                  }}>
                    <Image
                      src={logo.svg}
                      alt={logo.label}
                      width={200}
                      height={200}
                      style={{ width: '100%', height: 'auto', display: 'block' }}
                    />
                  </div>
                  {/* Info + buttons */}
                  <div style={{ padding: 'var(--s-4)' }}>
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 'var(--s-2)',
                      marginBottom: 'var(--s-3)',
                    }}>
                      <span style={{
                        width: '14px', height: '14px',
                        background: logo.swatch,
                        border: '1px solid rgba(255,255,255,0.15)',
                        flexShrink: 0,
                      }} />
                      <span style={{
                        fontFamily: 'var(--ff-label)',
                        fontSize: '11px',
                        fontWeight: 600,
                        letterSpacing: '0.12em',
                        textTransform: 'uppercase',
                        color: 'rgba(255,255,255,0.85)',
                      }}>{logo.label}</span>
                    </div>
                    <div style={{ display: 'flex', gap: 'var(--s-2)' }}>
                      <a href={logo.svg} download style={{
                        flex: 1,
                        fontFamily: 'var(--ff-label)',
                        fontSize: '11px',
                        fontWeight: 600,
                        letterSpacing: '0.1em',
                        textTransform: 'uppercase',
                        textAlign: 'center',
                        color: 'var(--c-text)',
                        background: 'rgba(255,255,255,0.06)',
                        padding: '10px 12px',
                        textDecoration: 'none',
                        transition: 'background var(--d-fast) var(--ease-in-out)',
                      }}
                        onMouseEnter={e => e.currentTarget.style.background = 'rgba(212,160,23,0.15)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.06)'}
                      >SVG</a>
                      <a href={logo.png} download style={{
                        flex: 1,
                        fontFamily: 'var(--ff-label)',
                        fontSize: '11px',
                        fontWeight: 600,
                        letterSpacing: '0.1em',
                        textTransform: 'uppercase',
                        textAlign: 'center',
                        color: 'var(--c-text)',
                        background: 'rgba(255,255,255,0.06)',
                        padding: '10px 12px',
                        textDecoration: 'none',
                        transition: 'background var(--d-fast) var(--ease-in-out)',
                      }}
                        onMouseEnter={e => e.currentTarget.style.background = 'rgba(212,160,23,0.15)'}
                        onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.06)'}
                      >PNG 1024</a>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── BAND KITS ─────────────────────────────────────────────── */}
        <section id="bands" style={{
          padding: 'clamp(60px, 10vw, 120px) var(--gutter-fluid)',
          borderBottom: '1px solid var(--c-border)',
        }}>
          <div style={{ maxWidth: 'var(--layout-max)', margin: '0 auto' }}>
            <div className="reveal" style={{ marginBottom: 'var(--s-7)' }}>
              <div className="section-label" style={{ marginBottom: 'var(--s-3)' }}>Band Kits</div>
              <h2 style={{
                fontFamily: 'var(--ff-display)',
                fontSize: 'clamp(40px, 6vw, 72px)',
                letterSpacing: '0.01em',
                lineHeight: 0.95,
                marginBottom: 'var(--s-3)',
              }}>One-Pagers · Photos · Contacts</h2>
              <p style={{
                fontFamily: 'var(--ff-body)',
                fontSize: 'clamp(14px, 1.6vw, 16px)',
                lineHeight: 1.7,
                fontWeight: 300,
                color: 'rgba(255,255,255,0.55)',
                maxWidth: '640px',
              }}>
                Each one-pager PDF is generated live from the same data on the band's site page, so it's always current. For high-res photos, hit the band's booking contact directly.
              </p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--s-5)' }}>
              {bandsList.map((band, i) => (
                <article
                  key={band.slug}
                  className={`reveal-up delay-${(i + 1) * 100}`}
                  style={{
                    border: '1px solid rgba(255,255,255,0.06)',
                    background: 'var(--c-bg)',
                    overflow: 'hidden',
                    position: 'relative',
                  }}
                >
                  {/* Top color bar */}
                  <div style={{ height: '3px', background: band.color }} />

                  <div className="press-band-grid" style={{
                    display: 'grid',
                    gridTemplateColumns: 'minmax(0, 280px) minmax(0, 1fr)',
                    gap: 0,
                    alignItems: 'stretch',
                  }}>
                    {/* Photo column */}
                    <div style={{
                      position: 'relative',
                      minHeight: '260px',
                      background: '#0a0a0a',
                      overflow: 'hidden',
                    }}>
                      {band.heroPhoto && (
                        <img
                          src={band.heroPhoto}
                          alt={band.name}
                          loading="lazy"
                          style={{
                            position: 'absolute', inset: 0,
                            width: '100%', height: '100%',
                            objectFit: 'cover',
                            objectPosition: band.heroObjectPosition || 'center center',
                          }}
                        />
                      )}
                      <div style={{
                        position: 'absolute', inset: 0,
                        background: `linear-gradient(180deg, transparent 40%, rgba(0,0,0,0.6) 100%)`,
                      }} />
                      {/* Band tag bottom-left */}
                      <div style={{
                        position: 'absolute', left: '16px', bottom: '16px',
                        fontFamily: 'var(--ff-label)',
                        fontSize: '10px',
                        fontWeight: 600,
                        letterSpacing: '0.15em',
                        textTransform: 'uppercase',
                        color: band.color,
                        background: 'rgba(0,0,0,0.6)',
                        backdropFilter: 'blur(6px)',
                        padding: '6px 10px',
                        border: `1px solid ${band.color}55`,
                      }}>{band.shortName}</div>
                    </div>

                    {/* Content column */}
                    <div style={{
                      padding: 'clamp(24px, 3vw, 40px)',
                      display: 'flex', flexDirection: 'column', gap: 'var(--s-3)',
                    }}>
                      <div>
                        <div style={{
                          fontFamily: 'var(--ff-label)',
                          fontSize: '10px',
                          fontWeight: 600,
                          letterSpacing: '0.18em',
                          textTransform: 'uppercase',
                          color: band.color,
                          marginBottom: '8px',
                        }}>{band.era}</div>
                        <h3 style={{
                          fontFamily: 'var(--ff-display)',
                          fontSize: 'clamp(32px, 4.5vw, 52px)',
                          letterSpacing: '0.02em',
                          lineHeight: 0.95,
                          color: 'var(--c-text)',
                          marginBottom: '6px',
                        }}>{band.name}</h3>
                        {band.tagline && (
                          <div style={{
                            fontFamily: 'var(--ff-body)',
                            fontSize: '15px',
                            fontStyle: 'italic',
                            color: 'rgba(255,255,255,0.5)',
                          }}>{band.tagline}</div>
                        )}
                      </div>

                      <p style={{
                        fontFamily: 'var(--ff-body)',
                        fontSize: '14.5px',
                        lineHeight: 1.7,
                        fontWeight: 300,
                        color: 'rgba(255,255,255,0.65)',
                        // 3-line clamp keeps the band cards roughly equal height.
                        display: '-webkit-box',
                        WebkitLineClamp: 4,
                        WebkitBoxOrient: 'vertical',
                        overflow: 'hidden',
                      }}>{band.description}</p>

                      {/* Genre chips */}
                      <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                        {band.genre.map(g => (
                          <span key={g} style={{
                            fontFamily: 'var(--ff-label)',
                            fontSize: '9px',
                            fontWeight: 600,
                            letterSpacing: '0.15em',
                            textTransform: 'uppercase',
                            color: band.color,
                            background: `${band.color}10`,
                            border: `1px solid ${band.color}30`,
                            padding: '5px 9px',
                          }}>{g}</span>
                        ))}
                      </div>

                      {/* Action row */}
                      <div style={{
                        display: 'flex',
                        gap: 'var(--s-2)',
                        flexWrap: 'wrap',
                        marginTop: 'var(--s-3)',
                        paddingTop: 'var(--s-3)',
                        borderTop: '1px solid rgba(255,255,255,0.06)',
                      }}>
                        <a href={`/api/press/${band.slug}`} target="_blank" rel="noopener noreferrer" style={{
                          fontFamily: 'var(--ff-label)',
                          fontSize: '11px',
                          fontWeight: 600,
                          letterSpacing: '0.12em',
                          textTransform: 'uppercase',
                          color: 'var(--c-bg)',
                          background: band.color,
                          padding: '11px 18px',
                          textDecoration: 'none',
                          display: 'inline-flex', alignItems: 'center', gap: '6px',
                          transition: 'opacity var(--d-fast) var(--ease-in-out)',
                        }}
                          onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
                          onMouseLeave={e => e.currentTarget.style.opacity = '1'}
                        >
                          One-Pager PDF
                          <span aria-hidden="true">↓</span>
                        </a>
                        <Link href={`/bands/${band.slug}`} style={{
                          fontFamily: 'var(--ff-label)',
                          fontSize: '11px',
                          fontWeight: 600,
                          letterSpacing: '0.12em',
                          textTransform: 'uppercase',
                          color: 'var(--c-text)',
                          padding: '11px 18px',
                          background: 'rgba(255,255,255,0.04)',
                          border: '1px solid rgba(255,255,255,0.08)',
                          textDecoration: 'none',
                          transition: 'border-color var(--d-fast) var(--ease-in-out)',
                        }}
                          onMouseEnter={e => e.currentTarget.style.borderColor = `${band.color}55`}
                          onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)'}
                        >Band Page →</Link>
                        <a href={`mailto:${band.bookingEmail}?subject=Press inquiry · ${band.name}`} style={{
                          fontFamily: 'var(--ff-label)',
                          fontSize: '11px',
                          fontWeight: 600,
                          letterSpacing: '0.12em',
                          textTransform: 'uppercase',
                          color: 'rgba(255,255,255,0.85)',
                          padding: '11px 18px',
                          background: 'transparent',
                          border: '1px solid rgba(255,255,255,0.08)',
                          textDecoration: 'none',
                          transition: 'border-color var(--d-fast) var(--ease-in-out), color var(--d-fast) var(--ease-in-out)',
                        }}
                          onMouseEnter={e => {
                            e.currentTarget.style.borderColor = `${band.color}55`
                            e.currentTarget.style.color = band.color
                          }}
                          onMouseLeave={e => {
                            e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)'
                            e.currentTarget.style.color = 'rgba(255,255,255,0.85)'
                          }}
                        >
                          {band.bookingEmail}
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
        </section>

        {/* ── HIGH-RES PHOTOS / PRESS INQUIRIES ─────────────────────── */}
        <section style={{
          padding: 'clamp(60px, 10vw, 120px) var(--gutter-fluid)',
        }}>
          <div style={{
            maxWidth: '880px', margin: '0 auto', textAlign: 'center',
          }}>
            <div className="reveal-up" style={{
              width: '32px', height: '3px',
              background: 'var(--c-epl)',
              margin: '0 auto var(--s-5)',
            }} />
            <div className="section-label reveal" style={{ marginBottom: 'var(--s-3)' }}>Need more?</div>
            <h2 className="reveal delay-100" style={{
              fontFamily: 'var(--ff-display)',
              fontSize: 'clamp(40px, 6vw, 72px)',
              letterSpacing: '0.01em',
              lineHeight: 0.95,
              marginBottom: 'var(--s-4)',
            }}>
              High-Res Photos &<br/>Custom Requests
            </h2>
            <p className="reveal-up delay-200" style={{
              fontFamily: 'var(--ff-body)',
              fontSize: 'clamp(15px, 1.7vw, 18px)',
              lineHeight: 1.7,
              fontWeight: 300,
              color: 'rgba(255,255,255,0.65)',
              marginBottom: 'var(--s-6)',
            }}>
              Need print-resolution band photos, stage plots, tech riders, or interview availability? Reach the band directly through the booking email above, or use our contact form and we'll route the request.
            </p>
            <div className="reveal-up delay-300" style={{
              display: 'flex', gap: 'var(--s-3)', justifyContent: 'center', flexWrap: 'wrap',
            }}>
              <Link href="/contact" style={{
                fontFamily: 'var(--ff-label)',
                fontSize: '12px',
                fontWeight: 600,
                letterSpacing: 'var(--ls-label-tight)',
                textTransform: 'uppercase',
                color: 'var(--c-bg)',
                background: 'var(--c-epl)',
                padding: '14px 28px',
                textDecoration: 'none',
                transition: 'opacity var(--d-fast) var(--ease-in-out)',
              }}
                onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
                onMouseLeave={e => e.currentTarget.style.opacity = '1'}
              >Contact Echo Play Live</Link>
              <a href="mailto:booking@echoplay.live?subject=Press inquiry" style={{
                fontFamily: 'var(--ff-label)',
                fontSize: '12px',
                fontWeight: 600,
                letterSpacing: 'var(--ls-label-tight)',
                textTransform: 'uppercase',
                color: 'var(--c-text)',
                background: 'transparent',
                border: '1px solid rgba(255,255,255,0.2)',
                padding: '13px 28px',
                textDecoration: 'none',
                transition: 'border-color var(--d-fast) var(--ease-in-out)',
              }}
                onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--c-epl)'}
                onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(255,255,255,0.2)'}
              >Email Press Desk</a>
            </div>
          </div>
        </section>

        <FaqSection items={FAQ_PRESS} heading="EPK FAQ" anchorId="faq" />

      </main>

      <style jsx global>{`
        @media (max-width: 720px) {
          .press-company-grid { grid-template-columns: 1fr !important; }
          .press-band-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>

      <Footer />
    </>
  )
}
